# Generated by Django 5.2.13 on 2026-05-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_oauth2", "0032_oauth2provider_grant_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizationcode",
            name="redirect_uri",
            field=models.TextField(default="", verbose_name="Redirect URI"),
        ),
    ]
