# Generated by Django 5.2.13 on 2026-05-03 16:40

import authentik.lib.generators
import authentik.lib.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_providers_oauth2", "0033_authorizationcode_redirect_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2provider",
            name="pushed_authorization_allow_any_redirect_uris",
            field=models.BooleanField(
                default=False,
                help_text="Whether to allow any Redirect URIs with Pushed Authorization Request.",
                verbose_name="Allow any Redirect URIs with Pushed Authorization Request",
            ),
        ),
        migrations.AddField(
            model_name="oauth2provider",
            name="require_pushed_authorization_requests",
            field=models.BooleanField(
                default=False,
                help_text="Whether to require clients using Pushed Authorization Request (RFC 9126) to pass parameters to authorize flow.",
                verbose_name="Require Pushed Authorization Request",
            ),
        ),
        migrations.CreateModel(
            name="PushedAuthorizationData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("expires", models.DateTimeField(default=None, null=True)),
                ("expiring", models.BooleanField(default=True)),
                (
                    "urn_local",
                    models.TextField(default=authentik.lib.generators.generate_id, unique=True),
                ),
                ("_data", models.TextField(default="", verbose_name="Data")),
                (
                    "_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentik_providers_oauth2.oauth2provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pushed Authorization Request Data",
                "verbose_name_plural": "Pushed Authorizations Request Data",
                "indexes": [
                    models.Index(fields=["expires"], name="authentik_p_expires_3069e7_idx"),
                    models.Index(fields=["expiring"], name="authentik_p_expirin_253260_idx"),
                    models.Index(
                        fields=["expiring", "expires"], name="authentik_p_expirin_91b88d_idx"
                    ),
                ],
            },
            bases=(authentik.lib.models.InternallyManagedMixin, models.Model),
        ),
    ]
